invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   a <- ursa_dummy(3)
   print(a)
   b1 <- ursa_stack(a[1:2],colorize(a[3],ramp=FALSE))
   print(b1)
   b2 <- as.list(a)
   print(b2)
   b3 <- list(a[1],a[2:3])
   print(b3)
   b31 <- lapply(b3,colorize,ramp=FALSE)
   print(b31)
   b32 <- ursa_apply(b3,colorize,ramp=FALSE,rev=TRUE)
   print(b32)
   s311 <- ursa_apply(b31,ursa_colortable)
   print(s311)
   s21 <- lapply(b2,global_mean)
   print(s21)
   s22 <- sapply(b2,global_mean)
   print(s22)
   s31 <- lapply(b3,global_mean)
   print(s31)
   s32 <- sapply(b3,global_mean)
   print(s32)
   c1 <- unlist(b1)
   print(c1)
   c2 <- unlist(b2)
   print(c2)
   c3 <- unlist(b3)
   print(if (is.ursa(c3)) c3 else "broken object")
   d3 <- as.ursa(b3)
   print(if (is.ursa(d3)) d3 else "broken object")
})
