invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   session_grid(regrid(mul=1/16))
   a <- ursa_dummy(nband=3)
   ursa_info(a)
   print(dim(a))
   dim(a) <- c(25,00,34)
   print(dim(a))
   b <- create_envi("tmp1",bandname=letters[1:5],compress=FALSE)
   print(dim(b))
   close(b)
   envi_remove("tmp1")
})
