invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   data(volcano)
   pdf.start(pdfname())
   par(mfrow=c(2,2))
   image(volcano)
   a <- as.ursa(volcano)
   image(a)
  # plot(a)
   b <- as.array(a,drop=TRUE)
   image(b)
  # b <- as.array(a,drop=!TRUE)
  # image(b[,,1])
   d <- as.matrix(a,coords=TRUE)
   image(d)
   pdf.stop(pdfname())
})
