invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   session_grid(regrid(mul=1/16))
   a1 <- ursa_dummy(nband=2)
   names(a1) <-  weekdays(Sys.Date()+seq(length(a1))-1)
   a2 <- ursa_dummy(nband=2)
   names(a2) <- names(a1)
   print(a1)
   print(a2)
   a3 <- a1[1]
   print(names(a3))
   a4 <- c(today=a3)
   print(names(a4))
   print(b1 <- c(a1,a2))
   print(b2 <- c(a1=a1))
   print(b3 <- c(a1=a1,a2=a2))
   print(b5 <- c(a1=a1,a2=a2[1]))
   print(b4 <- c(a1,'(tomorrow)'=a1[2])) ## raster append
   print(b6 <- c(a1,50))
})
