invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   session_grid(regrid(mul=1/16))
   print(session_grid())
   a <- ursa_dummy(nband=5)
   print(a)
   print(seq(a))
   print(seq(a,"c"))
   print(seq(a,"x"))
   print(ursa_seqx())
})
