invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   a <- ursa_dummy(nband=6,min=0,max=255,mul=1/4)
   compose_open()
   compose_close()
   compose_open(a)
   compose_close()
   compose_open("rgb",fileout="tmp1")
   compose_plot(a[1:3])
   compose_close()
   Sys.sleep(3)
   a <- dir(pattern="tmp1.png")
   print(a)
   file.remove(a)
})
