invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   ftemp <- tempfile(pattern="",fileext="")
   fpath <- dirname(ftemp)
   fname <- basename(ftemp)
   a <- round(ursa_dummy(1,min=0,max=255,nodata=NA))
   write_envi(a,file.path(fpath,paste0(fname,"_1",".envi")))
   write_gdal(a,file.path(fpath,paste0(fname,"_2")))
   write_gdal(a,file.path(fpath,paste0(fname,"_3",".tif")))
   write_gdal(a,file.path(fpath,paste0(fname,"_4")),driver="EHdr")
   flist <- dir(path=fpath,pattern=fname,full.names=TRUE)
   file.remove(flist)
   blist <- basename(flist)
   res <- NULL
   for (i in seq(4))
      res <- c(res,paste(grep(paste0("_",i),blist,value=TRUE),collapse=" "))
   print(res)
})
