invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   if (FALSE) {
      fname2 <- system.file("pictures/test_envi_class.envi",package="rgdal")
      a <- read_gdal(fname2)
      ursa_colortable(a) <- paste0(ursa_colortable(a),"7F")
      print(ursa_colortable(a))
      write_gdal(a,"c:/tmp/res1.tif")
      write_gdal(a,"c:/tmp/res2.envi")
     # q()
   }
   fname1 <- system.file("pictures/cea.tif",package="rgdal")
   message(fname1)
   a1 <- open_gdal(fname1)
   print(a1)
   print(a1[])
   close(a1)
   fname2 <- system.file("pictures/test_envi_class.envi",package="rgdal")
   message(fname2)
   b1 <- open_gdal(fname2)
   b2 <- open_envi(fname2)
   print(b1)
   print(b2)
   print(c('The same grid?'=identical(ursa_grid(b1),ursa_grid(b2))
          ,'The same data?'=identical(ursa_value(b1[]),ursa_value(b2[]))))
   close(b1,b2)
})
