invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   a <- pixelsize()
   write_envi(a,"example")
   a <- open_envi("example")
   dir(pattern="^example.*")
   ursa_info(a)
   close(a)
   rm(a)
   envi_remove("example")

   ## additional arguments are enough to create new ENVI file
   dir(pattern="^example.*")
   a <- open_envi("example",layername=paste0("test",1:3))
   ursa_info(a)
   dir(pattern="^example.*")
   close(a)
   envi_remove("example")
})
