invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   set.seed(500)
   a.brick <- a.stack <- ursa_dummy(nband=3,min=0,max=255)
   a.stack[2] <- a.stack[2]/10
   a.stack[3] <- sqrt(a.stack[3])
   a.rgb <- as.integer(round(a.brick))
  # print(a.brick)
  # print(a.stack)
   print(a.rgb)
  # display(a.brick)
  # display(a.stack)
   display(a.rgb)
})
