invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   a1 <- create_envi("tmp1.envi")
   a2 <- create_envi("tmp2.")
   close(a1,a2)
   print(envi_list())
   envi_copy("tmp1","tmp3")
   envi_copy("tmp2","tmp4")
   print(envi_list())
   envi_rename("tmp3","tmp5")
   print(envi_list())
   envi_exists("nofilewithsuchname")
   envi_exists("tmp[34]")
   envi_remove(".+")
   print(envi_list())
})
