invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   set.seed(352)
   a <- as.integer(ursa_dummy(3,min=0,max=999))
   ind <- which(ursa_value(a[1])==890)
   print(ind)
   msk <- a[1]==890
   am <- a[msk]
   b <- as.data.frame(am)
   b$jx <- b$x+runif(nrow(b),min=-1000,max=1000)
   b$jy <- b$y+runif(nrow(b),min=-1000,max=1000)
   print(b)
   cr1 <- coord_xy(a,x=b$jx,y=b$jy)
   cr2 <- coord_xy(a,y=b$y,x=b$x)
   cr3 <- coord_xy(a,ind=ind)
   print(cr1)
   print(all.equal(cr1,cr2,cr3))
   xy1 <- coord_cr(a,c=cr1["c",],r=cr1["r",])
   print(xy1)
   print(c(identical(unname(xy1["x",]),b[,"x",drop=TRUE])
          ,identical(unname(xy1["y",]),b[,"y",drop=TRUE])))
   val1 <- value_xy(a,x=b$jx,y=b$jy)
   val2 <- value_xy(a,x=b$x,y=b$y)
   val3 <- value_cr(a,ind=ind)
   val4 <- value_cr(a,c=cr1["c",],r=cr1["r",])
   print(val1)
   print(all.equal(val1,val2,val3,val4))
   ps <- pixelsize()
   ll <- c(lon=180,lat=70)
   v <- value_ll(ps,lon=180,lat=70)
   print(c('True scale'=v/with(ursa_grid(ps),1e-6*resx*resy)))
})
