invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   a <- ursa_dummy(2,min=-40,max=80)
   a[a<0] <- NA
   print(a)
   a.mean <- global_mean(a)
   a.sd <- global_sd(a)
   a.sum <- global_sum(a)
   a.min <- global_min(a)
   a.max <- global_max(a)
   a.median <- global_median(a)
   print(c(mean=a.mean,sd=a.sd,sum=a.sum,min=a.min,max=a.max,median=a.median))
   v.max <- max(ursa_value(a),na.rm=TRUE)
   print(c('global_max()'=a.max,'max(ursa_value())'=v.max,dif=a.max-v.max))
   r.max <- global_max(a,ursa=TRUE)
   print(r.max)
   b <- c(a,'appended scalar value'=a.max)
   print(b)
})
