plutil::mysource(ursa)
#'local_min' <- function(...) .syn('local_extrem',0,...)
invisible({
   session_grid(NULL)
   a <- ursa_dummy(nband=2,mul=1/8,elements=32)#,elements=0)
   ##~ str(as.matrix(a[1]))
   ##~ str(as.matrix(a[2]))
   ##~ str(a[[1]])
   ##~ str(a[[2]])
   ##~ pdf.start(pdfname())
   ##~ image(a[[1]],asp=1)
   ##~ filled.contour(a[[1]],asp=1)
   ##~ pdf.stop(pdfname())
   ##~ q()
   a[a<80] <- NA
   b.min <- focal_extrem(a,"min",size=4,cover=0.5,verbose=1L)
   b.max <- focal_extrem(a,"max",size=4,cover=0.5,verbose=1L)
   print(list(src=a,min=b.min,max=b.max,dif=b.max-b.min))
})
