invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   a <- pixelsize()
   val <- c(normal=a,half=a/2)
   gr <- c(group=colorize(a,nbreak=1))#+0
   print(as.table(gr))
   ##~ display(gr)
   ra <- round(aggregate(val,gr,mean),4)
   print(ra)
   print(as.table(ra[1]))
   print(as.table(ra[2]))
   da <- aggregate(val,gr,table=TRUE,mean)
   n <- aggregate(a,gr,table=TRUE,length)[,2,drop=FALSE]
   da <- cbind(da,n=unname(n))
   print(da)
   gr2 <- c(group2=colorize(a,nbreak=6))#+0
   mgr <- list(gr,gr2)
   da2 <- aggregate(val[1],mgr,table=TRUE,mean)
   print(da2)
   da3 <- aggregate(val,mgr,table=TRUE,mean)
   print(da3)
   ra3 <- aggregate(val,mgr,table=FALSE,mean)
   print(ra3)
   display(ra3)
})
