invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   s <- substr(as.character(sessionInfo()),1,48)
   a <- reclass(ursa_dummy(bandname=s),ramp=FALSE)
   ##~ write_envi(a,"c:/tmp/res1.envi");q()
   band_stat(a,grid=TRUE)
   b2 <- band_stat(a)
   b3 <- band_stat(a,raw=TRUE)
   str(b2)
   str(b3)
   print(b2)
   print(a) ## 'print.ursaRaster' uses 'band_stat'
   print(a,raw=TRUE)
})
