invisible({
   plutil::mysource(ursa)
   session_grid(NULL)
   require(rgdal)
   require(methods)
   a <- pixelsize()
   g1 <- session_grid()
   n <- 12L
   k <- 5L
   x <- with(g1,runif(n,min=minx,max=maxx))
   y <- with(g1,runif(n,min=miny,max=maxy))
  # panel_plot(x,y) ## plots nothing, because 'compose_open(...,dev=F)' is not called yet
   sl <- lapply(seq(k),function(id){
      x <- sort(with(g1,runif(n,min=minx,max=maxx)))
      y <- sort(with(g1,runif(n,min=miny,max=maxy)))
      sp::Lines(sp::Line(cbind(x,y)),ID=id)
   })
   sl <- sp::SpatialLines(sl,proj4string=sp::CRS(ursa_proj(g1)))#,id=length(sl))
   lab <- t(sapply(sp::coordinates(sl),function(xy) xy[[1]][round(n/2),]))
   lab <- as.data.frame(cbind(lab,z=seq(k)))
   sl <- sp::SpatialLinesDataFrame(sl
                 ,data=data.frame(ID=runif(k,min=5,max=9),desc=LETTERS[seq(k)]))
   print(sl@data)
   ct <- colorize(sl@data$ID)#,stretch="linear")#,name=sldf@data$desc)
  # pdf.start(pdfname())
  # plot(sl)
  # pdf.stop(pdfname())
   shpname <- tempfile(pattern = "___tmp",tmpdir=".",fileext=".shp")
   layername <- gsub("\\.shp$","",basename(shpname))
   try(writeOGR(sl,dirname(shpname),layername,driver="ESRI Shapefile"))
   sl1 <- sl[1:ceiling(k/2),]
  # sl2 <- readOGR(dirname(shpname),layername)[(nrow(sl1)+1):k,]
   compose_open(layout=c(1,2),legend=list(list("bottom",2)))
   panel_new()
   panel_decor()
   panel_lines(x,y,col="orange")
   panel_points(x,y,cex=5,pch=21,col="transparent",bg="#00FF005F")
   panel_points(0,0,pch=3)
   panel_text(0,0,"North\nPole",pos=4,cex=1.5,family="Courier New",font=3)
   panel_new()
   panel_decor()
   panel_plot(sl,lwd=4,col="grey20",add=TRUE)
   if (file.exists(shpname))
      panel_plot(shpname,lwd=3,col=ct$colortable[ct$index])
   panel_points(lab$x,lab$y,pch=as.character(lab$z),cex=2)
   compose_legend(ct$colortable)
   compose_close()
   file.remove(dir(path=dirname(shpname)
                  ,pattern=paste0(layername,"\\.(cpg|dbf|prj|shp|shx)")
                  ,full.names=TRUE))
   print("OK")
})
